export const ICONS = {
    LOGO: '/images/logo.png',
    SEARCH: '/icons/search.png',
    FACEBOOK: '/icons/facebook.png',
    INSTAGRAM: '/icons/instagram.png',
    NOTIFICATION_BELL: '/icons/notification_bell.png',
    INBOX: '/icons/message.png',
    SHOPPING_CART: '/icons/shopping_cart.png',
    TEST_ACCOUNT: '/icons/test_account.png',
    FREE_SHIPPING: '/icons/free_shipping.png',
    SHIPPED: '/icons/shipped.png',
    SECURE_PAYMENT: '/icons/secure_payment.png',
    SUPPORT: '/icons/support.png',
    SHOP: '/icons/shop.png',
}