spring:
  application:
    name: api


  #Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ebasket
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10


  #JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 10
        order_insert: true
        order_updates: true
    open-in-view: false


#Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
  show-actuator: false
  group-configs:
    - group: eBasket API
      paths-to-match: /api/**
      packages-to-scan: com.eBasket.api

